config/routes.rb
SampleApp4::Application.routes.draw do
  
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home'
  
  match '/about', to: 'static_pages#about', via: [:get, :post]
  match '/contact', to: 'static_pages#contact', via: [:get, :post]
  match '/help', to: 'static_pages#help', via: [:get, :post]
  match '/home', to: 'static_pages#home', via: [:get, :post]
  
  match '/signup', to: 'users#new', via: [:get, :post]
  match '/signin', to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: [:delete] #restrict to HTTP DELETE request
  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
	<div class="container">
		<small>
			<a href="http://www.google.com">Google</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", 	about_path %></li>
				<li><%= link_to "Contact", 	contact_path %></li>
			</ul>
		</nav>
	</div>
</footer>
			

app/views/layouts/_header.html.erb
<!-- a shim to handle all the headers -->

<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<nav class="navbar navbar-default" role="navigation">
				<ul class="nav navbar-nav navbar-left">
					<li><%= link_to "sample app", '/', id: "logo"%></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", 	home_path %></li>
					<li><%= link_to "Help", 	help_path %></li>
					<!-- OK, so here's our conditional formatting based on signin status -->
					<% if signed_in? %>
					<li> <%= link_to "Users", '#' %> </li>
					<li id="fat-menu" class="dropdown" >
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" >
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu"> 
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", '#' %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>
					<% else %>
						<li>
							<%= link_to "Sign in", signin_path %>
						</li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
	<head>
		<title><%= full_title(yield(:title))%></title>
		<%= stylesheet_link_tag		"application", media: "all" %>
		<%= javascript_include_tag	"application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<!-- this is kind of ugly, but allows us to show anything stored in the special "flash" hash -->
			<!-- NB that it doesn't actually show errors, only the confirmation message styled with the "success" class. -->
			<% flash.each do |key, value| %>
			<!-- we can do this a different way, as seen below. 
				<div class="alert alert-<%= key %>"><%= value %></div>
			-->
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
		</div>	
		<%= render 'layouts/footer'%>	
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>